version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: AccesaInternship
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1337
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/AccesaInternship
      DATASOURCE_USER: postgres
      DATASOURCE_PASS: 1337

volumes:
  pgdata:
