services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "7777:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_USER=${DATASOURCE_USER}
      - DATASOURCE_PASS=${DATASOURCE_PASS}

volumes:
  postgres_data:
